### ISSUE TITLE
m1 pro的MacBook pro、Mac os12安装时提示无法安装

### ISSUE THREAD

**Issue by zhanglubin721** [hybriddb/Hammervpn#2]

**Comment by slayerwalt** [comment]
我这里M1 Macbook Air也是不行

**Comment by zhanglubin721** [comment]
那大概率应该就是mac os 12的问题，导致无法安装。电脑上用不了，手机开vpn给电脑开热点很难受啊

**Comment by fenfenjin** [comment]
IOS登录显示Beta版已过期，是什么原因？

**Comment by zhanglubin721** [comment]
> IOS登录显示Beta版已过期，是什么原因？
就是过期了，不能用了，官方也没回应好像，可能是放弃了

**Comment by hybriddb** [comment]
> _No description provided._

已经修复 

MAC下载地址
https://hm-1304018649.cos.ap-hongkong.myqcloud.com/Hammer_Macos.pkg

IOS下载地址
https://www.msjt.org/?1118

**Comment by hybriddb** [comment]
> > IOS登录显示Beta版已过期，是什么原因？
> > 就是过期了，不能用了，官方也没回应好像，可能是放弃了

怎么可能放弃？

**Comment by hybriddb** [comment]
> IOS登录显示Beta版已过期，是什么原因？

> _No description provided._

已经修复 

MAC下载地址
https://hm-1304018649.cos.ap-hongkong.myqcloud.com/Hammer_Macos.pkg

IOS下载地址
https://www.msjt.org/?1118

**Comment by hybriddb** [comment]
> 那大概率应该就是mac os 12的问题，导致无法安装。电脑上用不了，手机开vpn给电脑开热点很难受啊

已经修复 

MAC下载地址
https://hm-1304018649.cos.ap-hongkong.myqcloud.com/Hammer_Macos.pkg

IOS下载地址
https://www.msjt.org/?1118

**Comment by hybriddb** [comment]
> 我这里M1 Macbook Air也是不行

已经修复 

MAC下载地址
https://hm-1304018649.cos.ap-hongkong.myqcloud.com/Hammer_Macos.pkg

IOS下载地址
https://www.msjt.org/?1118

**Comment by zhanglubin721** [comment]
官方很负责，但是如果再早点我就不会被superfast骗30块了T_T
